import { Router } from "express";
import { z } from "zod";

const router = Router();

const RequestSchema = z.object({
  format: z.enum(["html", "json"]),
  data: z.record(z.unknown()),
  title: z.string().optional(),
});

function generateHtml(data: Record<string, unknown>, title: string): string {
  const now = new Date().toLocaleString();
  const jsonStr = JSON.stringify(data, null, 2);

  function getUrl(): string {
    return (data.url as string) ?? "Unknown URL";
  }

  function renderSection(key: string, value: unknown): string {
    if (Array.isArray(value)) {
      if (value.length === 0) return `<p style="color:#888">No data available</p>`;
      return `<table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead>
          <tr style="background:#1a2740">
            ${Object.keys(value[0] as object).map(k => `<th style="padding:8px 12px;text-align:left;color:#94a3b8;border-bottom:1px solid #334155">${k}</th>`).join("")}
          </tr>
        </thead>
        <tbody>
          ${value.map((row, i) => `<tr style="background:${i % 2 === 0 ? "#0f172a" : "#111827"}">
            ${Object.values(row as object).map(v => `<td style="padding:8px 12px;border-bottom:1px solid #1e2d40;color:#e2e8f0">${String(v ?? "")}</td>`).join("")}
          </tr>`).join("")}
        </tbody>
      </table>`;
    }
    if (typeof value === "object" && value !== null) {
      return `<pre style="background:#0f172a;padding:12px;border-radius:6px;overflow:auto;font-size:12px;color:#94a3b8">${JSON.stringify(value, null, 2)}</pre>`;
    }
    return `<span style="color:#e2e8f0">${String(value)}</span>`;
  }

  const sections = Object.entries(data)
    .filter(([k]) => !["url", "scannedAt", "testedAt"].includes(k))
    .map(([key, value]) => {
      const label = key.replace(/([A-Z])/g, " $1").replace(/^./, s => s.toUpperCase());
      return `
      <div style="margin-bottom:32px">
        <h2 style="font-size:16px;color:#38bdf8;border-bottom:1px solid #1e2d40;padding-bottom:8px;margin-bottom:16px">${label}</h2>
        ${renderSection(key, value)}
      </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - Security Toolkit Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #060c18; color: #e2e8f0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px 20px; }
    .container { max-width: 1000px; margin: 0 auto; }
    .header { background: linear-gradient(135deg, #0f172a, #1a2740); border: 1px solid #1e3a5f; border-radius: 12px; padding: 32px; margin-bottom: 32px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
    .badge-green { background: #052e16; color: #22c55e; border: 1px solid #166534; }
    .badge-blue { background: #0c1a2e; color: #38bdf8; border: 1px solid #0284c7; }
    .card { background: #0f172a; border: 1px solid #1e2d40; border-radius: 10px; padding: 24px; margin-bottom: 24px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div style="display:flex;justify-content:space-between;align-items:start">
        <div>
          <div style="font-size:11px;color:#475569;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:8px">Security Toolkit</div>
          <h1 style="font-size:28px;font-weight:700;color:#f1f5f9;margin-bottom:8px">${title}</h1>
          <p style="color:#64748b;font-size:14px">Target: <span style="color:#38bdf8">${getUrl()}</span></p>
        </div>
        <div style="text-align:right">
          <span class="badge badge-green">Report Generated</span>
          <p style="color:#475569;font-size:12px;margin-top:8px">${now}</p>
        </div>
      </div>
    </div>

    <div class="card">
      ${sections}
    </div>

    <div class="card">
      <h2 style="font-size:16px;color:#38bdf8;margin-bottom:16px">Raw Data</h2>
      <pre style="background:#060c18;padding:16px;border-radius:6px;overflow:auto;font-size:12px;color:#64748b;max-height:400px">${jsonStr}</pre>
    </div>

    <div style="text-align:center;color:#334155;font-size:12px;margin-top:32px">
      Generated by Security Toolkit &bull; ${now}
    </div>
  </div>
</body>
</html>`;
}

router.post("/report/export", async (req, res) => {
  const parsed = RequestSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: "Invalid request" });
  }

  const { format, data, title = "Security Report" } = parsed.data;
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);

  if (format === "json") {
    return res.json({
      format: "json",
      content: JSON.stringify(data, null, 2),
      filename: `security-report-${timestamp}.json`,
    });
  }

  const htmlContent = generateHtml(data, title);
  return res.json({
    format: "html",
    content: htmlContent,
    filename: `security-report-${timestamp}.html`,
  });
});

export default router;
